spring:
  datasource:
    url: jdbc:postgresql://trolley.proxy.rlwy.net:29857/railway
    username: postgres
    password: nmgecoSENcGXeiJRGYoFhNJjEoTRfxOg
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect